---
title: "Plot TMLE Results"
author: "Jingzhi Kevin Yu"
date: "2025-03-25"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)

tmle_results_df = fread('/Users/excenity/Documents/HSIP/Research/Dissertation Project/Results/results_030725/tmle_results_df/at_control_14090.csv')
```

clean dataset
```{r}
tmle_results_df$sbp = 'SBP≥150mmHg'
tmle_results_df$sbp[grep('150,300', tmle_results_df$patient_profiles)] = 'SBP<150mmHg'

tmle_results_df$bmi = 'BMI<30'
tmle_results_df$bmi[grep('30,100', tmle_results_df$patient_profiles)] = 'BMI≥30'

tmle_results_df$age = '65+ Y/O'
tmle_results_df$age[grep('0,65', tmle_results_df$patient_profiles)] = '<65 Y/O'

tmle_results_df$pp_label = paste(tmle_results_df$sbp, '/', tmle_results_df$bmi, '/', tmle_results_df$age)
```

Plots
```{r, fig.width = 15, fig.height=8}
TMLE_plot = ggplot2::ggplot(tmle_results_df, ggplot2::aes(x = htn_med_class, y = Q1_star_avg, color = htn_med_class)) +
  ggplot2::geom_point() +
  ggplot2::geom_linerange(ggplot2::aes(ymin=Q1_star_lb, ymax=Q1_star_ub)) +
  ggplot2::facet_wrap('pp_label', nrow = 2) +
  ggplot2::theme_bw() + 
  ggplot2::theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1), text=element_text(size=16)) +
  ggplot2::xlab('Hypertension Medication Class') +
  ggplot2::ylab('Predicted Treatment Effect') 
TMLE_plot
```
