---
title: "HTN HTE Analysis"
author: "Jingzhi Kevin Yu"
date: "4/15/24"
output: html_document
---

```{r, setup}
if (!require(SuperLearner))
{
  install.packages("SuperLearner")
}

library(HTNHTE)
library(DatabaseConnector)
library(SqlRender)
library(SuperLearner)
library(tidyverse)

# medication type list
htn_med_list = c('acei', 'arb', 'ccb', 'diuretic', 'ccb_combo', 'diuretic_combo')
```

# Part 1
1. Cohort Extraction
2. Creating Analytic Dataset
3. Statistical Analysis Step 1, 2 

```{r}
##### PLEASE EDIT ##### 
connectionDetails = createConnectionDetails(
  dbms = "postgresql",
  server = 'localhost/HTN_OMOP',
  user = 'postgres',
  password = '741China@',
  pathToDriver = '/Users/excenity/Library/R/jdbcDrivers'
)


executeStudy(
    connectionDetails = connectionDetails,
    cdmDatabaseSchema = 'htnhte',
    cohortDatabaseSchema = 'htnhte',
    cohortTable = 'htn_hte',
    outputpath = '/Users/excenity/Documents/HSIP/Research/Dissertation Project/Results/results_022825',
    generateCohorts = T,
    extractingData = T,
    runStatisticsAnalysis = T,
    runTreatmentEffects = F
)
```


## -- STOP HERE AND REVIEW RESULTS OF STEP 2 -- ## 

## PART 2: Use targeted estimation to determine treatment effects of BP medications

# STEP 3: Targeted Maximum Likelihood Estimation (TMLE) of Medication Treatment Effects within Different Patient Populations
```{r}
cont_var = c('sbp', 'ldl', 'age', 'bmi')

cutpoints = list(c(0, 150, 300),
                 c(0 ,100, 300),
                 c(0, 65, 150),
                 c(0, 30, 100))


### Create Learners for SL
# random forest
RF.learners = SuperLearner::create.Learner("SL.ranger", tune = list(mtry = 3, num.trees = 500), detailed_names = T)
# xgboost
tune = list(ntrees = c(5, 10, 15),
            max_depth = 2:5,
            eta = c(0.1, 0.05, 0.01))
xgboost.learners = SuperLearner::create.Learner("SL.xgboost", tune = tune, detailed_names = T, name_prefix = "xgb")
# elastic net
enet = SuperLearner::create.Learner("SL.glmnet", detailed_names = T, tune = list(alpha = seq(0, 1, length.out = 5)))
# list libraries
SL.library.chosen = c("SL.mean", "SL.glm", "SL.glm.interaction", RF.learners$names, xgboost.learners$names, enet$names)

print(SL.library.chosen)


executeStudy(
    connectionDetails = connectionDetails,
    cdmDatabaseSchema = 'htnhte',
    cohortDatabaseSchema = 'htnhte',
    cohortTable = 'htn_hte',
    outputpath = '/Users/excenity/Documents/HSIP/Research/Dissertation Project/Results/results_081824',
    generateCohorts = F,
    extractingData = F,
    runStatisticsAnalysis = F,
    runTreatmentEffects = T,
    cont_var = cont_var,
    cutpoints = cutpoints
)
```
