
path = getwd()
dir.create(file.path(path, 'results'), showWarnings = F)
dir.create(file.path(path, 'results/step0_datasetCreation'), showWarnings = F)

#' Clean and wrangle dataset for analysis
#'
#' @details
#' This function loads a json file with all the study cohorts
#' that were created using ATLAS and then generates them in the
#' user specified OMOP CDM database
#'
#' @param data The data matrix generated by the generateCohort function
#'
#' @return
#' The cohorts are generated into the specified cohort schema and table
#'
#' @export
#'
generateAnalyticDataset = function(data)
{
  ## OHDSI Exports Cleaning

  # creating dataframe and headers
  df = as.data.frame(as.matrix(data$dataMatrix))
  df_headers = as.data.frame(data$covariateRef)

  headers = read.csv('inst/omop_headers.csv')
  headers = dplyr::inner_join(headers, df_headers)

  names(df) = headers$header

  ## Exclusions

  sink(file.path(path, 'results/step0_datasetCreation/CONSORT_postprocessing.txt'))
  print(paste('N Initial Dataset', nrow(df)))
  df = df %>% dplyr::filter(age >= 18)
  print(paste('N after removing those under age 18:', nrow(df)))
  df = df %>% dplyr::filter(sbp != 0 & dbp != 0 )
  print(paste('N after removing missing baseline BP measurement:', nrow(df)))
  df = df %>% dplyr::filter(sbp_6m != 0 & dbp_6m != 0)
  print(paste('N after removing missing outcome at 6 months:', nrow(df)))
  df = df %>% dplyr::filter(sbp >= 140 | dbp >= 90)
  print(paste('N after removing those at control at prescription:', nrow(df)))
  sink()

  ## Wrangle Demographic Variables

  # combine asian races
  df$asian = ifelse(df$asian + df$pacific_islander + df$american_indian + df$asian_indian + df$chinese +
                      df$filipino + df$japanese + df$korean + df$vietnamese + df$other_pacific >= 1, 1, 0)
  df = df %>% select(-c('pacific_islander', 'american_indian', 'asian_indian', 'chinese', 'filipino', 'japanese', 'korean', 'vietnamese', 'other_pacific'))

  df$pid = 1:nrow(df)
  race_df = df %>% select('pid', 'asian', 'black', 'white') %>% pivot_longer(cols = c('asian', 'black', 'white'), values_to = 'race')
  race_df = race_df %>% filter(race == 1) %>% select('pid', 'name')
  names(race_df)[2] = 'race'
  df = left_join(df, race_df)
  df$race[is.na(df$race)] = 'other'
  df$race[df$race_unknown == 1] = NA
  df = df %>% select(-c('asian', 'black', 'white', 'race_unknown'))

  # combine ethnicities
  df = df %>% select(-'non-hispanic')

  # combine genders
  df$male[df$gender_unknown == 1] = NA
  df$gender = df$male
  df = df %>% select(-c('female', 'gender_unknown', 'male'))


  ## Medication Assignment

  # create individual dual combo classes
  df$acei_diuretic[df$acei == 1 & df$diuretic == 1] = 1
  df$acei_ccb[df$acei == 1 & df$ccb == 1] = 1
  df$arb_diuretic[df$arb == 1 & df$diuretic == 1] = 1
  df$arb_ccb[df$arb == 1 & df$ccb == 1] = 1

  df[is.na(df)] = 0

  # create broad combo classes
  df$diuretic_combo = ifelse(df$acei_diuretic == 1 | df$arb_diuretic == 1, 1, 0)
  df$ccb_combo = ifelse(df$acei_ccb == 1 | df$arb_ccb == 1, 1, 0)

  # remove those with more than 3 classes
  df = df %>% filter(diuretic_combo + ccb + bb < 2)
  df = df %>% filter(ccb_combo + diuretic + bb < 2)

  # reset single medication classes for dual therapies
  df$acei[df$diuretic_combo == 1 | df$ccb_combo == 1] = 0
  df$arb[df$diuretic_combo == 1 | df$ccb_combo == 1] = 0
  df$ccb[df$diuretic_combo == 1 | df$ccb_combo == 1] = 0
  df$diuretic[df$diuretic_combo == 1 | df$ccb_combo == 1] = 0

  ## combine variables
  med_class_df = df %>% select(pid, acei, arb, bb, ccb, diuretic, ccb_combo, diuretic_combo) %>% pivot_longer(cols = acei:diuretic_combo, names_to = 'htn_med_class', values_to = 'value') %>% filter(value == 1)
  med_class_list = med_class_df %>% group_by(pid) %>% count()
  med_class_list = med_class_list %>% filter(n < 3)
  med_class_list_otherCombo = med_class_list %>% filter(n == 2) %>% distinct(pid)
  med_class_df$htn_med_class[med_class_df$pid %in% med_class_list_otherCombo$pid] = 'other_combo'
  med_class_df = med_class_df %>% filter(pid %in% med_class_list$pid) %>% distinct()
  df = inner_join(df, med_class_df %>% select(-value))
  df = df %>% select(-c(acei, acei_diuretic, acei_ccb, arb, arb_diuretic, arb_ccb, bb, ccb, diuretic, acei_diuretic, acei_ccb, arb_ccb, diuretic_combo, ccb_combo))
  df$htn_med_class[is.na(df$htn_med_class)] = 'other'

  ## Bound lab values
  # Bounding BMI, total cholesterol, and creatinine
  df$bmi[df$bmi < 12 | df$bmi > 100] = NA
  df$bmi_neg[df$bmi_neg < 12 | df$bmi_neg > 100] = NA
  df$chol[df$chol < 100 | df$chol > 300] = NA
  df$ldl[df$ldl < 10 | df$ldl > 250] = NA
  df$hba1c[df$hba1c < 4.5] = 5
  df$hba1c[df$hba1c > 15] = 15
  df$creatinine[df$creatinine < 0.5  | df$creatinine > 5] = NA

  ### MISSINGNESS ###

  ## missingness visualizations and tables

  png(file.path(path, 'results/step0_datasetCreation/missmap.png'), width = 800, height = 600)
  Amelia::missmap(df)
  dev.off()

  sink(file.path(path, 'results/step0_datasetCreation/missingness_df.txt'))
  print(colSums(is.na(df)))
  sink()

  # normalization
  norm_vars = c('bmi', 'chol', 'creatinine', 'bmi_neg', 'ldl')
  norm_process = caret::preProcess(df %>% select(norm_vars), method = 'range')
  norm_df = predict(norm_process, df %>% select(norm_vars))
  df[, norm_vars] = norm_df

  ## Missing Imputation
  mice_df = mice::mice(df %>% select(-c(pid)), m = 1, maxit = 100, method = 'pmm', seed = 618, verbose = F)
  png(file.path(path, 'results/step0_datasetCreation/imputation.png'), width = 800, height = 600)
  mice::densityplot(mice_df)
  dev.off()

  norm_df = mice::complete(mice_df) %>% select(norm_vars)

  # rescale
  ranges = norm_process$ranges[2,] - norm_process$ranges[1,]
  for (i in 1:length(ranges))
  {
    norm_df[,i] = norm_df[,i] * ranges[i]
    norm_df[,i] = norm_df[,i] + norm_process$ranges[1, i]
  }

  # combine imputed data with full dataset
  mice_df = mice::complete(mice_df)
  mice_df = mice_df %>% select(-norm_vars)
  mice_df = cbind(mice_df, norm_df)

  df = cbind(df %>% select(c(pid)), mice_df)

  ### Outcome Determination ###

  # SBP change in 6 months
  df$sbp_change = df$sbp_6m - df$sbp

  # BP Goal 140/90
  df$bp_14090 = ifelse(df$sbp_6m < 140 & df$dbp_6m < 90, 1, 0)
  df$bp_13080 = ifelse(df$sbp_6m < 130 & df$dbp_6m < 80, 1, 0)

  # BMI negative control
  df$bmi_neg = df$bmi_neg - df$bmi

  ### Convert Data Types ###

  factor_list = c('gender', 'race', 'hispanic', 'hf', 'dm', 'ckd', 'sleep_apnea',"antidepressants", "hormonal_therapy", "statins", "ppi")
  df = df %>% mutate_at(factor_list, as.factor)
  df$htn_med_class = as.character(df$htn_med_class)
  df = df %>% select(-c(sbp_6m, dbp_6m))

  return(df)
}


