#' Clean and wrangle dataset for analysis
#'
#' @details
#' This function loads a json file with all the study cohorts
#' that were created using ATLAS and then generates them in the
#' user specified OMOP CDM database
#'
#' @param data The data matrix generated by the generateCohort function
#' @param outputpath The location to save results to
#'
#' @return
#' The cohorts are generated into the specified cohort schema and table
#'
#' @export
#'
generateAnalyticDataset = function(
    data,
    outputpath = './results/step0_datasetCreation'
    )
{

  if(!dir.exists(outputpath)){
    dir.create(outputpath, recursive = T)
  }
  ## OHDSI Exports Cleaning

  # creating dataframe and headers
  df = as.data.frame(as.matrix(data$dataMatrix))
  df_headers = as.data.frame(data$covariateRef)

  headers = read.csv(system.file('omop_headers.csv',package = 'HTNHTE'))
  headersInData = dplyr::inner_join(headers, df_headers)

  # restrict to columns in the csv file
  df <- df[,headersInData$columnId]
  names(df) = headersInData$header

  # add any missing columns
  missingHeaders <- headers$header[!headers$header %in% colnames(df)]
  if(length(missingHeaders) > 0){
    for(missingHeader in missingHeaders){
      # add race
      df$newCol <- NA
      colnames(df)[colnames(df) == 'newCol'] <- missingHeader
    }
  }

  ## Wrangle Demographic Variables

  # combine Asian races
  df$asian = ifelse(df$asian + df$pacific_islander + df$american_indian + df$asian_indian + df$chinese +
                      df$filipino + df$japanese + df$korean + df$vietnamese + df$other_pacific >= 1, 1, 0)
  df = df %>% dplyr::select(-c('pacific_islander', 'american_indian', 'asian_indian', 'chinese', 'filipino', 'japanese', 'korean', 'vietnamese', 'other_pacific'))

  df$pid = 1:nrow(df)
  race_df = df %>% dplyr::select('pid', 'asian', 'black', 'white') %>%
    tidyr::pivot_longer(
      cols = c('asian', 'black', 'white'),
      values_to = 'race'
    )
  race_df = race_df %>%
    dplyr::filter(.data$race == 1) %>%
    dplyr::select('pid', 'name')
  names(race_df)[2] = 'race'
  df = dplyr::left_join(x = df, y = race_df)
  df$race[is.na(df$race)] = 'other'
  df$race[df$race_unknown == 1] = NA
  df = df %>% dplyr::select(-c('asian', 'black', 'white', 'race_unknown'))

  # combine ethnicities
  df = df %>% dplyr::select(-'non-hispanic')

  # combine genders
  df$male[df$gender_unknown == 1] = NA
  df$gender = df$male
  df = df %>% dplyr::select(-c('female', 'gender_unknown', 'male'))

  ## outcomes missingness comparison
  sink(file.path(outputpath, 'missingness_diff.txt'))
  df_miss_outcome = df
  col_repl = c('age', 'sbp', 'dbp', 'chol', 'ldl', 'creatinine', 'bmi_neg', 'hba1c', 'sbp_6m', 'dbp_6m', 'bmi')
  df_miss_outcome[col_repl] = sapply(df_miss_outcome[col_repl], function(x) replace(x, x %in% c(0), NA))
  df_miss_outcome$missing_outcome = ifelse(is.na(df_miss_outcome$sbp_6m) | is.na(df_miss_outcome$dbp_6m), 1, 0)
  t1 = tableone::CreateTableOne(data = df_miss_outcome, strata = 'missing_outcome', test = F)
  print(t1, smd = T)
  remove(df_miss_outcome)
  sink()

  sink(file.path(outputpath, 'consort.txt'))

  ## Exclusions
  print(paste('N Initial Dataset', nrow(df)))
  df = df %>% dplyr::filter(.data$age >= 18)
  print(paste('N after removing those under age 18:', nrow(df)))
  df = df %>% dplyr::filter(.data$sbp != 0 & .data$dbp != 0)
  print(paste('N after removing missing baseline BP measurement:', nrow(df)))
  df = df %>% dplyr::filter(.data$sbp_6m != 0 & .data$dbp_6m != 0)
  print(paste('N after removing missing outcome at 6 months:', nrow(df)))
  df = df %>% dplyr::filter(.data$sbp >= 140 | .data$dbp >= 90)
  print(paste('N after removing those at control at prescription:', nrow(df)))
  sink()

  ## Medication Assignment

  # create individual dual combo classes
  df$acei_diuretic[df$acei == 1 & df$diuretic == 1] = 1
  df$acei_ccb[df$acei == 1 & df$ccb == 1] = 1
  df$arb_diuretic[df$arb == 1 & df$diuretic == 1] = 1
  df$arb_ccb[df$arb == 1 & df$ccb == 1] = 1

  df[is.na(df)] = 0

  # create broad combo classes
  df$diuretic_combo = ifelse(df$acei_diuretic == 1 | df$arb_diuretic == 1, 1, 0)
  df$ccb_combo = ifelse(df$acei_ccb == 1 | df$arb_ccb == 1, 1, 0)

  # remove those with more than 3 classes
  df = df %>% dplyr::filter(diuretic_combo + ccb + bb < 2)
  df = df %>% dplyr::filter(ccb_combo + diuretic + bb < 2)

  # reset single medication classes for dual therapies
  df$acei[df$diuretic_combo == 1 | df$ccb_combo == 1] = 0
  df$arb[df$diuretic_combo == 1 | df$ccb_combo == 1] = 0
  df$ccb[df$diuretic_combo == 1 | df$ccb_combo == 1] = 0
  df$diuretic[df$diuretic_combo == 1 | df$ccb_combo == 1] = 0

  ## combine variables

  med_class_df = df %>%
    dplyr::select("pid", "acei", "arb", "bb", "ccb", "diuretic", "ccb_combo", "diuretic_combo") %>%
    tidyr::pivot_longer(
      cols = acei:diuretic_combo,
      names_to = 'htn_med_class',
      values_to = 'value'
      ) %>% dplyr::filter(.data$value == 1)
  med_class_list = med_class_df %>%
    dplyr::group_by(.data$pid) %>%
    dplyr::count() %>%
    #dplyr::filter(.data$n==1) %>%
    dplyr::filter(.data$n < 3) #%>%
    #dplyr::select("pid")

  # new code added that had conflict
  med_class_list_otherCombo = med_class_list %>%
  dplyr::filter(n == 2) %>%
  dplyr::distinct("pid")
  med_class_df$htn_med_class[med_class_df$pid %in% med_class_list_otherCombo$pid] = 'other_combo'

  med_class_df = med_class_df %>%
    dplyr::filter(.data$pid %in% med_class_list$pid) %>%
    dplyr::distinct()
  df = dplyr::inner_join(df, med_class_df %>% dplyr::select(-"value"))
  df = df %>% dplyr::select(-c("acei", "acei_diuretic", "acei_ccb", "arb", "arb_diuretic", "arb_ccb", "bb", "ccb", "diuretic", "acei_diuretic", "acei_ccb", "arb_ccb", "diuretic_combo", "ccb_combo"))

  df$htn_med_class[is.na(df$htn_med_class)] = 'other'

  df = df %>% dplyr::filter(!htn_med_class %in% c('other', 'other_combo'))

  ### MISSINGNESS (BMI) ###

  ## missingness visualizations and tables

  png(file.path(outputpath, 'missmap.png'), width = 800, height = 600)
  Amelia::missmap(df)
  dev.off()

  sink(file.path(outputpath, 'missingness_df.txt'))
  print(colSums(is.na(df)))
  sink()

  ## Bound lab values

  # Bounding BMI, total cholesterol, and creatinine
  df$bmi[df$bmi == 0] = NA
  df$bmi[df$bmi < 12] = 12
  df$bmi[df$bmi > 100] = 100
  df$bmi_neg[df$bmi_neg == 0] = NA
  df$bmi_neg[df$bmi_neg < 12] = 12
  df$bmi_neg[df$bmi_neg > 100] = 100

  df$bmi_neg[df$bmi_neg < 12] = 12
  df$bmi_neg[df$bmi_neg > 100] = 100

  df$hba1c[df$hba1c < 4.5] = 5
  df$hba1c[df$hba1c > 15] = 15

  ## Lab Panel Assignment (Creatinine, Total Cholesterol, LDL-C)

  df$creatinine[df$creatinine == 0 | df$creatinine > 3] = NA
  df$creatinine[is.na(df$creatinine)] = mean(df$creatinine, na.rm = T)

  df$chol[df$chol == 0 ] = NA
  df$chol[df$chol > 400] = 400
  df$chol[is.na(df$chol)] = mean(df$chol, na.rm = T)
  df$hyperlipid[df$chol > 240] = 1

  df$ldl[df$ldl == 0 ] = NA
  df$ldl[df$ldl > 250] = 250
  df$ldl[is.na(df$ldl)] = mean(df$ldl, na.rm = T)

  # normalization
  norm_vars = c('bmi', 'bmi_neg')
  norm_process = caret::preProcess(df %>% dplyr::select(norm_vars), method = 'range')
  norm_df = stats::predict(norm_process, df %>% dplyr::select(norm_vars))
  df[, norm_vars] = norm_df

  ## Missing Imputation
  mice_df = mice::mice(df %>% dplyr::select(-c("pid")), m = 1, maxit = 100, method = 'pmm', seed = 618, verbose = F)
  png(file.path(outputpath, 'imputation.png'), width = 800, height = 600)
  mice::densityplot(mice_df)
  dev.off()

  norm_df = mice::complete(mice_df) %>%
    dplyr::select(norm_vars)

  # rescale
  ranges = norm_process$ranges[2,] - norm_process$ranges[1,]
  for (i in 1:length(ranges))
  {
    norm_df[,i] = norm_df[,i] * ranges[i]
    norm_df[,i] = norm_df[,i] + norm_process$ranges[1, i]
  }

  # combine imputed data with full dataset
  mice_df = mice::complete(mice_df)
  mice_df = mice_df %>% dplyr::select(-norm_vars)
  mice_df = cbind(mice_df, norm_df)

  df = cbind(df %>% dplyr::select(c("pid")), mice_df)

  ### Outcome Determination ###

  # SBP change in 6 months
  df$sbp_change = df$sbp_6m - df$sbp

  # BP Goals
  df$bp_14090 = ifelse(df$sbp_6m < 140 & df$dbp_6m < 90, 1, 0)
  df$bp_13080 = ifelse(df$sbp_6m < 130 & df$dbp_6m < 80, 1, 0)

  # BMI negative control
  df$bmi_neg = df$bmi_neg - df$bmi

  ### Convert Data Types ###

  factor_list = c('gender', 'race', 'hispanic', 'hf', 'dm', 'ckd', 'sleep_apnea',"antidepressants", "hormonal_therapy", "statins", "ppi")
  df = df %>% dplyr::mutate_at(factor_list, as.factor)
  df$htn_med_class = as.character(df$htn_med_class)
  df = df %>% dplyr::select(-c("sbp_6m", "dbp_6m"))

  sink(file.path(outputpath, 'tableone.txt'))
  t1 = tableone::CreateTableOne(data = df)
  print(t1)
  sink()

  return(df)
}


